"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TASK_METADATA = exports.TASK_TESTNET = exports.TASK_TEST_SETUP_TEST_ENVIRONMENT = exports.TASK_TEST_GET_TEST_FILES = exports.TASK_TEST_RUN_MOCHA_TESTS = exports.TASK_TEST = exports.TASK_NODE_SERVER_READY = exports.TASK_NODE_SERVER_CREATED = exports.TASK_NODE_CREATE_SERVER = exports.TASK_NODE_GET_PROVIDER = exports.TASK_NODE = exports.TASK_RUN = exports.TASK_HELP = exports.TASK_FLATTEN_GET_DEPENDENCY_GRAPH = exports.TASK_FLATTEN_GET_FLATTENED_SOURCE = exports.TASK_FLATTEN = exports.TASK_CONSOLE = exports.TASK_COMPILE_INK_RUN_GENERATE_METADATA = exports.TASK_COMPILE_INK_RUN_COMPILER = exports.TASK_COMPILE_INK_GET_COMPILER_INPUT = exports.TASK_COMPILE_INK_ARTIFACTS = exports.TASK_COMPILE_SOLANG_OUTPUT = exports.TASK_COMPILE_SOLANG_EXEC = exports.TASK_COMPILE_SOLANG_INPUT = exports.TASK_COMPILE_SOLANG_PRE = exports.TASK_COMPILE_SOLANG = exports.TASK_COMPILE_INK_OUTPUT = exports.TASK_COMPILE_INK_EXEC = exports.TASK_COMPILE_INK_INPUT = exports.TASK_COMPILE_INK_PRE = exports.TASK_COMPILE_INK = exports.TASK_COMPILE = exports.TASK_CLEAN_GLOBAL = exports.TASK_CLEAN = exports.TASK_CHECK = void 0;
exports.TASK_CHECK = 'check';
exports.TASK_CLEAN = 'clean';
exports.TASK_CLEAN_GLOBAL = 'clean:global';
// export const TASK_COMPILE = 'compile';
// export const TASK_COMPILE_SOLANG = 'compile:solang';
// export const TASK_COMPILE_INK = 'compile:ink';
// export const TASK_COMPILE_INK_COMPILE = 'compile:ink:compile';
// export const TASK_COMPILE_INK_GET_RESOLVED_WORKSPACE =
//   'compile:ink:get-resolved-workspace';
// export const TASK_COMPILE_INK_ARTIFACTS = 'compile:ink:build-artifacts';
// export const TASK_COMPILE_INK_GET_COMPILER_INPUT =
//   'compile:ink:get-compile-input';
// export const TASK_COMPILE_INK_RUN_COMPILER = 'compile:ink:run-compiler';
// export const TASK_COMPILE_INK_RUN_GENERATE_METADATA =
//   'compile:ink:run-generate-metadata';
exports.TASK_COMPILE = 'compile';
exports.TASK_COMPILE_INK = 'compile:ink';
exports.TASK_COMPILE_INK_PRE = 'compile:ink:pre';
exports.TASK_COMPILE_INK_INPUT = 'compile:ink:input';
exports.TASK_COMPILE_INK_EXEC = 'compile:ink:exec';
exports.TASK_COMPILE_INK_OUTPUT = 'compile:ink:output';
exports.TASK_COMPILE_SOLANG = 'compile:solang';
exports.TASK_COMPILE_SOLANG_PRE = 'compile:solang:pre';
exports.TASK_COMPILE_SOLANG_INPUT = 'compile:solang:input';
exports.TASK_COMPILE_SOLANG_EXEC = 'compile:solang:exec';
exports.TASK_COMPILE_SOLANG_OUTPUT = 'compile:solang:output';
exports.TASK_COMPILE_INK_ARTIFACTS = 'compile:ink:build-artifacts';
exports.TASK_COMPILE_INK_GET_COMPILER_INPUT = 'compile:ink:get-compile-input';
exports.TASK_COMPILE_INK_RUN_COMPILER = 'compile:ink:run-compiler';
exports.TASK_COMPILE_INK_RUN_GENERATE_METADATA = 'compile:ink:run-generate-metadata';
exports.TASK_CONSOLE = 'console';
exports.TASK_FLATTEN = 'flatten';
exports.TASK_FLATTEN_GET_FLATTENED_SOURCE = 'flatten:get-flattened-sources';
exports.TASK_FLATTEN_GET_DEPENDENCY_GRAPH = 'flatten:get-dependency-graph';
exports.TASK_HELP = 'help';
exports.TASK_RUN = 'run';
exports.TASK_NODE = 'node';
exports.TASK_NODE_GET_PROVIDER = 'node:get-provider';
exports.TASK_NODE_CREATE_SERVER = 'node:create-server';
exports.TASK_NODE_SERVER_CREATED = 'node:server-created';
exports.TASK_NODE_SERVER_READY = 'node:server-ready';
exports.TASK_TEST = 'test';
exports.TASK_TEST_RUN_MOCHA_TESTS = 'test:run-mocha-tests';
exports.TASK_TEST_GET_TEST_FILES = 'test:get-test-files';
exports.TASK_TEST_SETUP_TEST_ENVIRONMENT = 'test:setup-test-environment';
exports.TASK_TESTNET = 'testnet';
exports.TASK_METADATA = 'metadata';
